name: Check-in

on:
  workflow_dispatch:

jobs:
  execute:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Execute main script
        env:
          account_id: ${{ secrets.ACCOUNT_ID }}
          account_id_v2: ${{ secrets.ACCOUNT_ID_V2 }}
          account_mid_v2: ${{ secrets.ACCOUNT_MID_V2 }}
          cookie_token: ${{ secrets.COOKIE_TOKEN }}
          cookie_token_v2: ${{ secrets.COOKIE_TOKEN_V2 }}
          ltmid_v2: ${{ secrets.LTMID_V2 }}
          ltoken_v2: ${{ secrets.LTOKEN_V2 }}
          ltuid_v2: ${{ secrets.LTUID_V2 }}
        run: python main.py